### ISSUE TITLE
建议在README中添加标题 115 网盘 Aria2 助手

### ISSUE THREAD

**Issue by FreeyW** [tces1/Aria2-Helper-for-115#11]
之前的2.1脚本过期无法使用了
https://greasyfork.org/  上也下架了这款脚本
搜索 115 网盘 Aria2 助手 在google也搜不到
误打误撞搜索tces1 才找到github的主页看到了更新2.2
这么好用的脚本应该让更多人知道
感谢

**Comment by tces1** [comment]
Thanks
