### ISSUE TITLE
这几天貌似又不行了

### ISSUE THREAD

**Issue by Wings168** [tces1/Aria2-Helper-for-115#12]
发送到aria2，下载都是0B，直接失败

**Comment by oklong** [comment]
我的还可以啊

**Comment by Wings168** [comment]
> 我的还可以啊

大文件试过吗？电影之类的，我这边一发送过去就显示403，然后直接停止了下载，我朋友的电脑也是一样，chrome浏览器

**Comment by oklong** [comment]
> 

经我这段时间的使用，是偶尔行偶尔不行
