### ISSUE TITLE
aria2 按钮消失了

### ISSUE THREAD

**Issue by levelel** [tces1/Aria2-Helper-for-115#4]
登录网盘后，选取资源，几天前还有的aria2按钮消失了。可能是脚本被115屏蔽了吧？

**Comment by tyhunter** [comment]
可能是脚本太多导致互相冲突了，你试着关闭仅保留这个脚本，我的还能看见

**Comment by tces1** [comment]
刚刚更新的就是按钮消失的问题，我测了下感觉没问题了 你把代码拷进去刷新试试吧

**Comment by levelel** [comment]
原来用的Mac Firefox，刚特地用纯净的Mac Chrome测试，只开一个插件，还是没有按钮。

**Comment by tces1** [comment]
你用最新的Aria2-Helper-for-115.js 去覆盖了吗

**Comment by levelel** [comment]
嗯，昨天的版本。https://post.smzdm.com/p/akmg3xer/ 这个帖子底下也有人反映没按钮了。
edit: 今天想起来，在Firefox里强制刷新了一下（Command+Shift+R)，现在可以用了。感谢！
